spring:
  datasource:
    url: jdbc:sqlite:./data/notedb.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  sql:
    init:
      mode: always
      platform: sqlite
      schema-locations: classpath:sqlite/schema.sql
      data-locations: classpath:sqlite/data.sql